#include "KoratCharacterDataAsset.h"

UKoratCharacterDataAsset::UKoratCharacterDataAsset() {
}

void UKoratCharacterDataAsset::Sort() {
}

void UKoratCharacterDataAsset::SetEffectHighSpeedMoveData() {
}

void UKoratCharacterDataAsset::SetDesignatedDataList() {
}

void UKoratCharacterDataAsset::SetChangeCharacterActionData() {
}

void UKoratCharacterDataAsset::GetNameArray(TArray<FName>& OutNames) const {
}

void UKoratCharacterDataAsset::GetDefaultItemsAndCostume(const FKoratCharacterDataList& InCharacter, TArray<FKoratCharacterItemDataList>& OutItems) {
}

void UKoratCharacterDataAsset::GetDefaultItems(const FKoratCharacterDataList& InCharacter, TArray<FKoratCharacterItemDataList>& OutItems) {
}

void UKoratCharacterDataAsset::GetDefaultCostume(const FKoratCharacterDataList& InCharacter, FKoratCharacterCostumeDataList& OutCostume) {
}

TArray<FKoratCharacterDataList> UKoratCharacterDataAsset::GetDebugAllCharacterDataList() const {
    return TArray<FKoratCharacterDataList>();
}

FText UKoratCharacterDataAsset::GetCharacterTitletName(const FName& InCharacterKey) const {
    return FText::GetEmpty();
}

FText UKoratCharacterDataAsset::GetCharacterShortName(const FName& InCharacterKey) const {
    return FText::GetEmpty();
}

FText UKoratCharacterDataAsset::GetCharacterFullName(const FName& InCharacterKey) const {
    return FText::GetEmpty();
}

FText UKoratCharacterDataAsset::GetCharacterEventName(const FName& InCharacterKey) const {
    return FText::GetEmpty();
}

bool UKoratCharacterDataAsset::CheckThrowAction(const FKoratActionDataList InAction) const {
    return false;
}

bool UKoratCharacterDataAsset::CheckSmashBulletAction(const FKoratActionDataList InAction) const {
    return false;
}

bool UKoratCharacterDataAsset::CheckRushBulletAction(const FKoratActionDataList InAction) const {
    return false;
}

bool UKoratCharacterDataAsset::CheckBlastAction(const FKoratActionDataList InAction) const {
    return false;
}

void UKoratCharacterDataAsset::Check() {
}

void UKoratCharacterDataAsset::AutoGenerateDataAsset() {
}

void UKoratCharacterDataAsset::AutoGenerateCostumeAndModelNames() {
}


