#include "SSBannerDataAsset.h"

USSBannerDataAsset::USSBannerDataAsset() {
    this->SortId = 0;
    this->BannerState = ESSBannerState::Enable;
}

void USSBannerDataAsset::AutoGenerateDataAsset() {
}


