#include "SSBattleIdleCameraActor.h"

ASSBattleIdleCameraActor::ASSBattleIdleCameraActor(const FObjectInitializer& ObjectInitializer) : Super(ObjectInitializer) {
    this->bAvoidTerrainDisableArray.AddDefaulted(4);
    this->PhysicalDisparityDecayScaleCamLengthArray.AddDefaulted(4);
    this->PhysicalDisparityDecayScaleFocalLengthArray.AddDefaulted(4);
    this->PhysicalDisparityDecayScaleHeightArray.AddDefaulted(4);
    this->PhysicalDisparityDecayScaleBaseYawArray.AddDefaulted(4);
    this->PhysicalDisparityBoundScaleDecayRateArray.AddDefaulted(4);
    this->bLookAtNullOffsetTargetImitationArray.AddDefaulted(4);
    this->LookUpEnemySectionArray.AddDefaulted(4);
    this->RollScaleMax = 1.00f;
    this->RollScaleMaxDecayPerSec = 3.00f;
    this->RollScaleMaxMin = 0.25f;
    this->RollScaleMaxMax = 1.00f;
    this->StartPosAdjustForceEndTimeDefault = 0.50f;
    this->ForceBehind = false;
    this->ForceNoBehind = false;
    this->FarTurn = true;
    this->NearTurn = false;
    this->StopVelocityMin = 0.00f;
    this->CameraOffsetBaseScale = 0.80f;
    this->bCameraOffsetAutoScaleAspect = true;
    this->CameraOffsetAutoScaleBaseRate = 0.70f;
    this->DistanceCameraAngleLimitMin = 0.00f;
    this->bCameraBaseYaw = false;
    this->CameraBaseYawLagScale = 0.50f;
    this->CameraBaseYawMinArray.AddDefaulted(4);
    this->CameraBaseYawMax = 150.00f;
    this->CameraBaseYawRangeMin = 100.00f;
    this->CameraBaseYawRangeMax = 700.00f;
    this->PlayerOverCamAngle = 15.00f;
    this->DebugPlayerOverCamAngle = false;
    this->PlayerOverCamAngleScaleSideBySide = 0.50f;
    this->PlayerFronMoveAddCameraDecayRate = 0.80f;
    this->LatAngleAutoScale = true;
    this->LatAngleAutoScaleNear = 0.10f;
    this->LatAngleAutoScaleMiddle = 0.20f;
    this->LatAngleAutoScaleFar = 0.60f;
    this->LatAngleAutoScaleRangeNear = 100.00f;
    this->LatAngleAutoScaleRangeMiddle = 200.00f;
    this->LatAngleAutoScaleRangeFar = 700.00f;
    this->LimitDistanceMin = 0.00f;
    this->NewHorizonArgorizum = true;
    this->bNewTeleportArgorizm = true;
    this->TeleportCrossCameraRate = -0.25f;
    this->bDebugDrawTeleport = false;
    this->NewOverSkyArgorizum = true;
    this->bOverSkyEnterCircle = false;
    this->NewCamPositionZArgorizum = false;
    this->CamSpeedZMax = 50.00f;
    this->NowYawAngle = 0.00f;
    this->bNewYawPlayArgorizm = false;
    this->YawPlaySplitRateL = 0.20f;
    this->YawPlaySplitRateR = 0.80f;
    this->YawPlaySplitRateDefaultL = 0.20f;
    this->YawPlaySplitRateDefaultR = 0.80f;
    this->bYawPlaySplitRateAuto = true;
    this->YawPlaySplitRateAutoMin = 0.00f;
    this->YawPlaySplitRateAutoMax = 0.80f;
    this->YawPlaySplitRateAutoRangeMin = 200.00f;
    this->YawPlaySplitRateAutoRangeMax = 2000.00f;
    this->YawPlaySplitRateAutoQuietTimeMin = 1.00f;
    this->YawPlaySplitRateAutoQuietTime = 0.00f;
    this->YawPlaySplitRateAutoQuietDecayRate = 0.02f;
    this->bDebugDrawNewYawPlayArgorizm = false;
    this->NewPitchHeightPlayArgorizum = false;
    this->NowPitch = 0.00f;
    this->NowHeight = 0.00f;
    this->PitchPlaySpeedMax = 10.00f;
    this->bHeightPlaySplitRateAuto = true;
    this->HeightPlaySplitRateV = 0.25f;
    this->HeightPlaySplitRateAutoMin = 0.00f;
    this->HeightPlaySplitRateAutoMax = 0.60f;
    this->bPitchPlaySplitRateAuto = true;
    this->PitchPlaySplitRateU = 0.80f;
    this->PitchPlaySplitRateD = 0.20f;
    this->PitchPlaySplitRateDefaultU = 0.80f;
    this->PitchPlaySplitRateDefaultD = 0.20f;
    this->DebugDrawNewPitchHeightPlayArgorizum = false;
    this->NewLookingDownArgorizum = false;
    this->LookingDownPitchMax = 80.00f;
    this->LookingDownPitchMin = 10.00f;
    this->LookingDownPullCamOffsetScaleMax = 1.50f;
    this->NewLatPositionZArgorizum = false;
    this->NewLatPositionZArgorizumBugfix = true;
    this->LatPitchFovLimitScaleU = 0.50f;
    this->LatPitchFovLimitScaleD = 0.50f;
    this->LatPitchMoveZScaleU = 0.10f;
    this->LatPitchMoveZScaleD = 0.10f;
    this->LatHollizonPitchMoveEnable = true;
    this->LatHollizonPitchMin = 10.00f;
    this->LatHollizonPitchMove = 4.00f;
    this->NearPitchLimit = true;
    this->NearPitchLimitRangeNear = 100.00f;
    this->NearPitchLimitRangeFar = 500.00f;
    this->bMaxPitchLimit = true;
    this->MaxPitchUp = 30.00f;
    this->MaxPitchDown = -60.00f;
    this->bTurnFollowLatArgorizm = true;
    this->TurnFollowLatRate = 0.02f;
    this->TurnFollowLatNearRange = 1000.00f;
    this->bOverlapEnemyArgorizm = false;
    this->DelayOverlapAngleMaxTime = 0.50f;
    this->DelayOverlapAngleLagDecayScale = 0.25f;
    this->DelayOverlapAngleLagDecayBlendTime = 0.20f;
    this->bDelayOverlapAngle = false;
    this->DelayOverlapAngleStartTime = 0.00f;
    this->OverlapSphereScaleArray.AddDefaulted(4);
    this->OverlapAngleScaleSideBySide = 0.70f;
    this->OverlapAngleScale = 1.00f;
    this->bOverlapAngleScaleAuto = false;
    this->BaseBoundScale = 0.80f;
    this->BoundScaleCurrent = 1.00f;
    this->BoundScaleSmallPerFrame = 0.02f;
    this->BoundScaleBigPerFrame = 0.00f;
    this->bBoundScaleYFromVelocity = true;
    this->BoundScaleYFromVelocityMax = 1400.00f;
    this->bBoundScaleXFromVelocity = true;
    this->BoundScaleXFromVelocityMax = 2000.00f;
    this->bBoundScaleFluffyMove = false;
    this->BoundScaleFluffyMoveSteepPitch = 15.00f;
    this->bCalcZoomOutOffset = false;
    this->CalcZoomOutOffsetScale = 0.10f;
    this->bCalcZoomOutScale = false;
    this->CalcZoomOutScaleVelocityMax = 1400.00f;
    this->bSonicSway = false;
    this->bSonicSwayed = false;
    this->bDisableShakeSonicSway = false;
    this->bZBurstLagScaleAndReset = true;
    this->ZBurstLagScaleAndResetStartTime = 1.00f;
    this->bDistanceDecayLagScaleArray.AddDefaulted(4);
    this->DistanceDecayLagScaleMin = 0.30f;
    this->DistanceDecayLagScaleNearRange = 300.00f;
    this->DistanceDecayLagScaleFarRange = 600.00f;
    this->bLagConvergenceZBurstSmashEnable = true;
    this->LagConvergenceZBurstSmash = 8.00f;
    this->bLagConvergenceZBurstDashEnable = true;
    this->LagConvergenceZBurstDash = 8.00f;
    this->ZoomSections.AddDefaulted(3);
    this->ZoomSectionIndex = -1;
    this->ZoomSectionStartTime = 0.00f;
    this->ZoomTimeOut = 2.00f;
    this->ZoomOffsetScaleSonicSwayPlayer = 1.00f;
    this->ZoomOffsetScaleSonicSwayEnemy = 1.00f;
    this->ZoomOffsetScaleSonicSwayedPlayer = 1.00f;
    this->ZoomOffsetScaleSonicSwayedEnemy = 1.00f;
    this->bEnableChargeZoom = false;
    this->ChargeZoomSectionIndex = -1;
    this->ChargeZoomSectionStartTime = 0.00f;
    this->ChargeZoomSectionEndFadeTime = 0.00f;
    this->ChargeZoomSectionZoomFocalLengthScaleBake = 0.00f;
    this->ChargeZoomSectionZoomFocalLengthScale = 0.00f;
    this->bEnableExplosionHitZoom = false;
    this->ExplosionHitZoomSectionIndex = -1;
    this->ExplosionHitZoomSections.AddDefaulted(12);
    this->ExplosionHitZoomSectionStartTime = 0.00f;
    this->ExplosionHitZoomSectionEndFadeTime = 0.00f;
    this->RushLeaveStartTime = 0.00f;
    this->bDragonDashStatus = false;
    this->bTargetLockOn = false;
    this->MyCharaMoveSpeed = 1.00f;
    this->PreNowCamAnglePToE = 0.00f;
    this->DebugNowAngleEToCDeg = 0.00f;
    this->DebugTraceSpline = false;
    this->bDebugTargetActorDisplay = false;
    this->DebugNowYaw = 0.00f;
    this->DebugCameraToEnemyYaw = 0.00f;
    this->DebugCameraToEnemyLen = 0.00f;
    this->DebugTargetOverlapAngle = 0.00f;
    this->DebugSubAngle = 0.00f;
    this->DebugLatLerpState = 0;
    this->DebugStartPosAdjustForceEndTime = 0.00f;
    this->DebugBaseYawPToE = 0.00f;
    this->DebugNowCamAnglePToE = 0.00f;
    this->DebugCameraOffsetLen = 0.00f;
    this->DebugFovRadianLimit = 0.00f;
    this->bDebugDrawCameraYaw = false;
    this->bDebugImaginaryLineForcedCam = false;
    this->bDebugImaginaryLineForcedLat = false;
    this->LateStartCameraType = ENewBattleCameraType::NONE;
    this->TargetOverlapAngleEToL = 0.00f;
    this->bLagScaleDecayPitchRateEnable = false;
    this->LagScaleDecayPitchRate = 1.00f;
    this->LagScaleDecayPitchMin = 10.00f;
    this->LagScaleDecayPitchMax = 30.00f;
    this->LagScaleDecayPitchScaleMin = 1.00f;
    this->LagScaleDecayPitchScaleMax = 0.50f;
    this->bChargeMargin = false;
    this->ChargeMarginLastTime = 0.00f;
    this->bExplosionHitMargin = false;
    this->ExplosionHitLevel = ECameraZoomType::ZoomNone;
    this->ExplosionHitZoomSectionZoomFocalLengthScaleBake = 0.00f;
    this->ExplosionHitZoomSectionZoomFocalLengthScale = 0.00f;
    this->ExplosionHitMarginLastTime = 0.00f;
}


