#include "SSBannerDataAsset.h"

USSBannerDataAsset::USSBannerDataAsset() {
    this->SortId = 0;
    this->BannerState = ESSBannerState::Enable;
    this->DownloadTexture = NULL;
    this->Priority = 0;
}

void USSBannerDataAsset::AutoGenerateDataAsset() {
}


