#include "SSCharacterFilterDataAsset.h"

USSCharacterFilterDataAsset::USSCharacterFilterDataAsset() {
    this->SortId = 0;
    this->UseMode = EKoratSortFilterUseMode::Always;
}

void USSCharacterFilterDataAsset::AutoGenerateDataAsset() {
}


