#include "SSCharacterUiDataAsset.h"

USSCharacterUiDataAsset::USSCharacterUiDataAsset() {
    this->BattleSetupData = NULL;
    this->ShopMenuData = NULL;
    this->GalleryMenuData = NULL;
    this->UIActionData = NULL;
}

void USSCharacterUiDataAsset::AutoGenerateFaceChipDataAsset() {
}

void USSCharacterUiDataAsset::AutoGenerateDataAsset() {
}


