#include "SSCharacterFilterDataAsset.h"

USSCharacterFilterDataAsset::USSCharacterFilterDataAsset() {
    this->SortId = 0;
    this->bEventBonus = false;
    this->bFirstForm = false;
}

void USSCharacterFilterDataAsset::AutoGenerateDataAsset() {
}


