#include "SSCharacterCombativesDataAsset.h"

USSCharacterCombativesDataAsset::USSCharacterCombativesDataAsset() {
}

void USSCharacterCombativesDataAsset::Sort() {
}

int32 USSCharacterCombativesDataAsset::ReplaceWithUniqueParameter(const FString& InKeys, ESSCharacterCombativesDataAssetParamType InType, bool bIsCreate) {
    return 0;
}

int32 USSCharacterCombativesDataAsset::ReplaceWithCommonParameter(const FString& InKeys, ESSCharacterCombativesDataAssetParamType InType, bool bIsCreate) {
    return 0;
}

void USSCharacterCombativesDataAsset::Prepare() {
}

int32 USSCharacterCombativesDataAsset::DeleteElement(const FString& InKeys) {
    return 0;
}

int32 USSCharacterCombativesDataAsset::CopyElement(const USSCharacterCombativesDataAsset* InSoruce, const FString& InKeys) {
    return 0;
}

void USSCharacterCombativesDataAsset::Check() {
}

void USSCharacterCombativesDataAsset::AutoGenerateDataAsset() {
}


