#include "SSCharacterDataAsset.h"

USSCharacterDataAsset::USSCharacterDataAsset() {
}

void USSCharacterDataAsset::TestDamageModelSelect() {
}

void USSCharacterDataAsset::SetDesignatedDataList() {
}

void USSCharacterDataAsset::SetChangeCharacterActionData() {
}

bool USSCharacterDataAsset::ImportGeneralFateCombination(const TMap<FKoratCharacterDataList, EGeneralFateAttribute2>& InMap) {
    return false;
}

void USSCharacterDataAsset::FixedEffectBPEnumMap() {
}

void USSCharacterDataAsset::Check() {
}

void USSCharacterDataAsset::BatchAddSpecialFateDataMap() {
}

bool USSCharacterDataAsset::AutoSetGeneralFateDataMap(const FString& InCharacterId) {
    return false;
}

void USSCharacterDataAsset::AutoGenerateDataAsset() {
}


