#include "SSDramaticBattleCutEditorUIWindowItemFunctionSubtitle.h"

USSDramaticBattleCutEditorUIWindowItemFunctionSubtitle::USSDramaticBattleCutEditorUIWindowItemFunctionSubtitle() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionSubtitle* USSDramaticBattleCutEditorUIWindowItemFunctionSubtitle::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


