#include "SSDramaticBattleCutEditorInitialSelectUIWindowDisplayConditionDataAssetRecord.h"

FSSDramaticBattleCutEditorInitialSelectUIWindowDisplayConditionDataAssetRecord::FSSDramaticBattleCutEditorInitialSelectUIWindowDisplayConditionDataAssetRecord() {
    this->DisplayCondition = ESSDramaticBattleCutEditorInitialSelectUIWindowDisplayConditionType::Visible;
}

