#include "SSDramaticBattleCutEditorUIWindowItemFunctionSubtitleSpeaker.h"

USSDramaticBattleCutEditorUIWindowItemFunctionSubtitleSpeaker::USSDramaticBattleCutEditorUIWindowItemFunctionSubtitleSpeaker() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionSubtitleSpeaker* USSDramaticBattleCutEditorUIWindowItemFunctionSubtitleSpeaker::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


