#include "SSDramaticBattleCutEditorUIWindowDisplayConditionDataAssetRecord.h"

FSSDramaticBattleCutEditorUIWindowDisplayConditionDataAssetRecord::FSSDramaticBattleCutEditorUIWindowDisplayConditionDataAssetRecord() {
    this->DisplayCondition = ESSDramaticBattleCutEditorUIWindowDisplayConditionType::Visible;
}

