#include "SSDramaticBattleCutEditorUIWindowItemFunctionFacial.h"

USSDramaticBattleCutEditorUIWindowItemFunctionFacial::USSDramaticBattleCutEditorUIWindowItemFunctionFacial() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionFacial* USSDramaticBattleCutEditorUIWindowItemFunctionFacial::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


