#include "SSDramaticBattleCutEditorUIWindowItemFunctionLayerName.h"

USSDramaticBattleCutEditorUIWindowItemFunctionLayerName::USSDramaticBattleCutEditorUIWindowItemFunctionLayerName() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionLayerName* USSDramaticBattleCutEditorUIWindowItemFunctionLayerName::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


