#include "SSDramaticBattleCutEditorInitialSelectUIWindowItemFunctionCharacterIndex.h"

USSDramaticBattleCutEditorInitialSelectUIWindowItemFunctionCharacterIndex::USSDramaticBattleCutEditorInitialSelectUIWindowItemFunctionCharacterIndex() {
}

USSDramaticBattleCutEditorInitialSelectUIWindowItemFunctionCharacterIndex* USSDramaticBattleCutEditorInitialSelectUIWindowItemFunctionCharacterIndex::CreateAndInitialize(ESSDramaticBattleCutEditorFunctionOperationType InFunctionOperation, ESSDramaticBattleCutEditorFunctionParameterType InFunctionParameter, ASSDramaticBattleCutEditorInitialSelectUIController* InUIController) {
    return NULL;
}


