#include "SSDramaticBattleCutEditorUIWindowItemFunctionCutDuration.h"

USSDramaticBattleCutEditorUIWindowItemFunctionCutDuration::USSDramaticBattleCutEditorUIWindowItemFunctionCutDuration() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionCutDuration* USSDramaticBattleCutEditorUIWindowItemFunctionCutDuration::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


