#include "SSDramaticBattleCutEditorUIWindowItemFunctionBGMName.h"

USSDramaticBattleCutEditorUIWindowItemFunctionBGMName::USSDramaticBattleCutEditorUIWindowItemFunctionBGMName() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionBGMName* USSDramaticBattleCutEditorUIWindowItemFunctionBGMName::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


