#include "SSDramaticBattleCutEditorUIWindowItemFunctionCharacterSpecify.h"

USSDramaticBattleCutEditorUIWindowItemFunctionCharacterSpecify::USSDramaticBattleCutEditorUIWindowItemFunctionCharacterSpecify() {
    this->FocusedValue = ESSEventSceneCharacterTypeDE::Character00;
}

USSDramaticBattleCutEditorUIWindowItemFunctionCharacterSpecify* USSDramaticBattleCutEditorUIWindowItemFunctionCharacterSpecify::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


