#include "SSDramaticBattleCutEditorUIWindowItemFunctionCaptureThumbnail.h"

USSDramaticBattleCutEditorUIWindowItemFunctionCaptureThumbnail::USSDramaticBattleCutEditorUIWindowItemFunctionCaptureThumbnail() {
}

USSDramaticBattleCutEditorUIWindowItemFunctionCaptureThumbnail* USSDramaticBattleCutEditorUIWindowItemFunctionCaptureThumbnail::CreateAndInitialize(FSSDramaticBattleCutEditorUIWindowItemFunctionInitializeParameter InParameter) {
    return NULL;
}


