#include "SSDramaticBattleCutEditorInitialSelectUIWindowDialogButtonData.h"

FSSDramaticBattleCutEditorInitialSelectUIWindowDialogButtonData::FSSDramaticBattleCutEditorInitialSelectUIWindowDialogButtonData() {
    this->Function = ESSDramaticBattleCutEditorInitialSelectUIWindowDialogButtonFunctionType::None;
}

