#include "SSShopFloorDataAsset.h"

USSShopFloorDataAsset::USSShopFloorDataAsset() {
    this->SortId = 0;
    this->SaleState = ESSShopFloorSaleState::Open;
    this->UIFormat = ESSShopFloorUIFormat::SmallSize;
}

void USSShopFloorDataAsset::AutoGenerateDataAsset() {
}


