#include "SSShopBaseItemDataAsset.h"

USSShopBaseItemDataAsset::USSShopBaseItemDataAsset() {
    this->SortId = 0;
    this->SaleState = ESSShopItemSaleState::Sales;
    this->ContentsType = ESSShopContentsType::None;
}

void USSShopBaseItemDataAsset::AutoGenerateDataAsset() {
}


