#pragma once
#include "CoreMinimal.h"
#include "EBattleStatus.generated.h"

UENUM(BlueprintType)
enum class EBattleStatus : uint8 {
    Initial,
    Idle,
    BattleSetup,
    WaitForStart,
    Apear,
    CheckReadyForBattle,
    NetworkFence,
    SubstituteNetworkFence,
    BattleStart,
    Battle,
    WaitForScriptFinish,
    DummyPowerImpact,
    DummyPowerImpactGiant,
    DummyCrashImpact,
    DummySpeedImpact,
    DummyBlastImpact,
    CharacterChange,
    CharacterTaketurns,
    BodyChange,
    MapChange,
    CharacterDamageCostume,
    WaitForTutorialBattle,
    WaitForSettle,
    WaitForSettleDirection,
    Settle,
    LoadingResult,
    Result,
    WaitForRematch,
    WaitForRematchFailure,
    WaitForRematchRoomState,
    WaitFadeOutForClose,
    WaitForAbortInterruptCommon,
    WaitForAbortNetworkError,
    WaitForAbortMatched,
    WaitForClose,
    Finish,
    Reset,
    WaitForReset,
    OutGameInitial,
    OutGameCheckReady,
    OutGameStart,
    OutGame,
    TrainingAgain,
    WaitForTrainingAgainFadeOut,
    WaitForTrainingFadeIn,
    TrainingPositionReset,
    WaitForTrainingPositionResetFadeOut,
    WaitInterruptDialogEnd,
};

