#pragma once
#include "CoreMinimal.h"
#include "EKoratBattleDirectingActivate.generated.h"

UENUM(BlueprintType)
enum class EKoratBattleDirectingActivate : uint8 {
    None,
    Victory,
    Defeat,
    DefeatWithBadEnd,
    Activate,
    CpuThinkingChange,
    CpuLevelChange,
    CharacterChange,
    CharacteCoalescence,
    CharacteFormChange,
    HPGaugeRecovery,
    HPGaugeDamage,
    HPGaugeDirectSet,
    SPGaugeRecovery,
    SPGaugeDamage,
    SPGaugeDirectSet,
    SkillStockRecovery,
    FullRecovery,
    SureToHitBlast,
    OneShotDeadly,
    BGMChange,
    Voice,
    ZItem,
    StageChange,
    EventRequest,
    Conversation,
    DirectingTableChange,
    ResetElapsedTime,
    StopElapsedTimer,
    PlayElapsedTimer,
    BulletForbid,
    BulletAllow,
    BlastForbid,
    BlastAllow,
    FormChangeForbid,
    FormChangeAllow,
    TaketurnsForbid,
    TaketurnsAllow,
    Buff,
    PracticeReset,
    AiCommand,
    AiEnabled,
    PracticeEnable,
    DispUnlockBlast,
    DispUnlockFormChange,
    DispUnlockCoalescence,
    BlowoutBrakeTimeReduction,
    BattleHUDShow,
    DispClearConditions,
    PauseMenuUpdate,
};

