#pragma once
#include "CoreMinimal.h"
#include "ESSCstRequestCommand.generated.h"

UENUM(BlueprintType)
enum class ESSCstRequestCommand : uint8 {
    None,
    CharaMotionEntrySelect,
    CharaMotionStand,
    CharaMotionStandNonInterpolation,
    CharaMotionEntrySelectLP,
    CharaMotionLeave,
    CharaMotionEntryTop,
    CharaMotionNoEffectStand,
    CharaJumpSectionLP,
    FastIdleMotionChange,
    WaitCharaMotion,
    WaitCharaMotionToStandAll,
    WaitCameraInterpolate,
    WaitCharaLoading,
    WaitCharaCameraLoading,
    WaitBgCharaState,
    AddBgCharaState,
    AddRollbackCommands,
    CancelRollback,
    WaitRollbackCharacter,
    IncrementStartPlace,
    DitherFadeOutAll,
    DitherFadeIn,
    WaitDitherFade,
    ReplaceCharacter,
    ChangeRollbackCharacter,
    RemoveDisplayCharacter,
    HiddenSpawnCharacter,
    ResetPreviewCameraOffset,
    PlayCharaCamera,
    PlayAssignCharaCamera,
    DestroyOldCharacter,
    DelayOneFrame,
    DelayOneSecond,
    StopUiAction,
    ChangeNextState,
    WarpCharacter,
    WarpTopCharacter,
    ClearRollbackCharacter,
    RestoreRollbackCharacter,
    EnableHiddenCharacter,
    DisableHiddenCharacter,
    PlayFrameInBlindEffect,
    WaitBlindedSignal,
    PlayEntryCamera,
    PlayTeamLight,
    WaitOneshotCamera,
    PlayTeamTalk,
    ParallelRequest,
    CameraRequestDelayTime,
    WaitCameraRequestCmd,
    ResetCameraRequestCmd,
    InterruptRestriction,
    FocusTransformStop,
    FocusTransformPlay,
    FocusChangeLastMarker,
    RemoveDPOverCharacter,
    WaitCharaReader,
    Max,
};

