#pragma once
#include "CoreMinimal.h"
#include "KoratActionDataList.h"
#include "KoratCharacterCombinationDataAssetRecord.h"
#include "KoratCharacterDataList.h"
#include "MutualDataAsset.h"
#include "KoratCharacterCombinationDataAsset.generated.h"

UCLASS(Blueprintable)
class UKoratCharacterCombinationDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratCharacterDataList DefaultCharacterData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TMap<FKoratActionDataList, FKoratCharacterCombinationDataAssetRecord> Records;
    
    UKoratCharacterCombinationDataAsset();

    UFUNCTION(BlueprintCallable)
    void SetDesignatedDataList();
    
    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

