#pragma once
#include "CoreMinimal.h"
#include "KoratCharacterDataList.h"
#include "MutualDataAsset.h"
#include "SSMontageLevelSequenceArray.h"
#include "KoratMLSDataAsset.generated.h"

UCLASS(Blueprintable, MinimalAPI)
class UKoratMLSDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratCharacterDataList DefaultCharacterData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FSSMontageLevelSequenceArray MontageLevelSequence;
    
    UKoratMLSDataAsset();

    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

