#pragma once
#include "CoreMinimal.h"
#include "KoratCharacterCostumeDataList.h"
#include "MutualDataAsset.h"
#include "SSCharacterCostumeUiData.h"
#include "SSCharacterUiDataAsset.generated.h"

class UKoratBattleSetupTransitionDataAsset;
class UKoratCharacterUIActionDataAsset;
class UTexture2D;

UCLASS(Blueprintable)
class USSCharacterUiDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChip1P;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChip2P;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChipCharacterSelect1P;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChipCharacterSelect2P;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChipCharacterSelectTransform;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> FaceChipShop;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TMap<FKoratCharacterCostumeDataList, FSSCharacterCostumeUiData> CostumeUiData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    UKoratBattleSetupTransitionDataAsset* BattleSetupData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    UKoratBattleSetupTransitionDataAsset* ShopMenuData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    UKoratBattleSetupTransitionDataAsset* GalleryMenuData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    UKoratCharacterUIActionDataAsset* UIActionData;
    
    USSCharacterUiDataAsset();

    UFUNCTION(BlueprintCallable)
    void AutoGenerateFaceChipDataAsset();
    
    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

