#pragma once
#include "CoreMinimal.h"
#include "EKoratSortFilterUseMode.h"
#include "KoratCharacterAttributeTagDataList.h"
#include "KoratCharacterFigureDataList.h"
#include "KoratSeriesTitleDataList.h"
#include "KoratSpeciesDataList.h"
#include "MutualDataAsset.h"
#include "SSCharacterFilterDataAsset.generated.h"

UCLASS(Blueprintable)
class USSCharacterFilterDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 SortId;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FText Name;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    EKoratSortFilterUseMode UseMode;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratCharacterFigureDataList FigureData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratSpeciesDataList SpeciesData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratSeriesTitleDataList SeriesTitleData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratCharacterAttributeTagDataList AttributeTagData;
    
    USSCharacterFilterDataAsset();

    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

