#pragma once
#include "CoreMinimal.h"
#include "ESSCharacterCombativesDataAssetParamType.h"
#include "KoratActionDataList.h"
#include "KoratCharacterDataList.h"
#include "MutualDataAsset.h"
#include "SSCharacterCombativesDataAssetRecordParam.h"
#include "SSCharacterCombativesDataAsset.generated.h"

class USSCharacterCombativesDataAsset;

UCLASS(Blueprintable, MinimalAPI)
class USSCharacterCombativesDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratCharacterDataList DefaultCharacterData;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TMap<FName, FSSCharacterCombativesDataAssetRecordParam> PtrRecords2;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TMap<FKoratActionDataList, FSSCharacterCombativesDataAssetRecordParam> RecordsByDataList;
    
    USSCharacterCombativesDataAsset();

    UFUNCTION(BlueprintCallable)
    void Sort();
    
    UFUNCTION(BlueprintCallable)
    int32 ReplaceWithUniqueParameter(const FString& InKeys, ESSCharacterCombativesDataAssetParamType InType, bool bIsCreate);
    
    UFUNCTION(BlueprintCallable)
    int32 ReplaceWithCommonParameter(const FString& InKeys, ESSCharacterCombativesDataAssetParamType InType, bool bIsCreate);
    
    UFUNCTION(BlueprintCallable)
    void Prepare();
    
    UFUNCTION(BlueprintCallable)
    int32 DeleteElement(const FString& InKeys);
    
    UFUNCTION(BlueprintCallable)
    int32 CopyElement(const USSCharacterCombativesDataAsset* InSoruce, const FString& InKeys);
    
    UFUNCTION(BlueprintCallable)
    void Check();
    
    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

