#pragma once
#include "CoreMinimal.h"
#include "ESSShopContentsType.h"
#include "ESSShopFloorSaleState.h"
#include "ESSShopFloorUIFormat.h"
#include "KoratConversationDataList.h"
#include "KoratShopSalesItemDataList.h"
#include "MutualDataAsset.h"
#include "SSShopFloorDataAsset.generated.h"

class UTexture2D;

UCLASS(Blueprintable)
class USSShopFloorDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FKoratConversationDataList SystemVoice;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 SortId;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FText FloorName;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> IconTexture;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    ESSShopFloorSaleState SaleState;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    ESSShopFloorUIFormat UIFormat;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<ESSShopContentsType> SaleContentsType;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TArray<FKoratShopSalesItemDataList> SaleItems;
    
    USSShopFloorDataAsset();

    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

