#pragma once
#include "CoreMinimal.h"
#include "MutualDataAsset.h"
#include "SSStockItemDataAsset.generated.h"

class UTexture2D;

UCLASS(Blueprintable)
class USSStockItemDataAsset : public UMutualDataAsset {
    GENERATED_BODY()
public:
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 SortId;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FText ItemName;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    FText ItemExplainText;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    TSoftObjectPtr<UTexture2D> ItemThumbnail;
    
    UPROPERTY(BlueprintReadWrite, EditAnywhere, meta=(AllowPrivateAccess=true))
    int32 MaxStockNum;
    
    USSStockItemDataAsset();

    UFUNCTION(BlueprintCallable)
    void AutoGenerateDataAsset();
    
};

