#pragma once
#include "CoreMinimal.h"
#include "ESSKeyInputDebugType.generated.h"

UENUM(BlueprintType)
enum class ESSKeyInputDebugType : uint8 {
    BattleFreeCameraSelect,
    BattleFreeCameraMoveUp,
    BattleFreeCameraMoveDown,
    BattleFreeCameraMoveRight,
    BattleFreeCameraMoveLeft,
    BattleFreeCameraMoveFront,
    BattleFreeCameraMoveBack,
    BattleFreeCameraTarget,
    BattleFreeCameraRollRight,
    BattleFreeCameraRollLeft,
    BattleFreeCameraZoomIn,
    BattleFreeCameraZoomOut,
    BattleFreeCameraSpeedUp,
    BattleFreeCameraSpeedDown,
    BattleFreeCameraReset,
    BattleFreeCameraPrReset1,
    BattleFreeCameraPrReset2,
    BattleDebugLockOnChange,
    BattleDebugSwapPlayerControllerID,
    BattleDebugResetTransform,
    BattleDebugSaveTransform,
    BattleHUDDebugUIToggleVisible,
    BattleDebugPowerImpact,
    BattleDebugCrashImpact,
    BattleDebugSpeedImpact,
    BattleDebugBlastImpact,
    BattleDebugSuperZCounter,
    BattleDebugUltimateBlast,
    BattleDebugPlayAction,
    BattleDebugRevengeCounter,
    BattleDebugRevengeDash,
    BattleDebugNormalInputTiming,
    BattleDebugEasyInputTiming,
    BattleDebugRushCamera,
    BattleDebugLocomotionTilt,
    BattleDebugLocomotionBlow,
    BattleDebugSaveInputP1,
    BattleDebugSaveInputP2,
    BattleDebugReplayInputP1,
    BattleDebugReplayInputP2,
    Max,
};

